### ISSUE TITLE
Бесконечное 'slaves' 'balance'

### ISSUE THREAD

**Issue by Linegrite** [monosans/vk-slaves-bot#1]
После запуска скрипта, он начинает бесконечно спамить
'slaves'
'balance'
'slaves'
'balance'
'slaves'
'slaves'
'slaves'
'balance'
'slaves'

**Comment by monosans** [comment]
Написал о возможных причинах в README.

**Comment by monosans** [comment]
Добавил debug версию для людей с такой проблемой. Инструкция по ее использованию в README.

**Comment by monosans** [comment]
Узнал, как можно попробовать пофиксить. Когда приду с учебы, выпущу обновление.

**Comment by dmitrashk** [comment]
Будем ждать

**Comment by PyluOtBabylu** [comment]
У меня поссле фикса заработал

**Comment by monosans** [comment]
Выложил фикс.
