### ISSUE TITLE
Slaves, Balance

### ISSUE THREAD

**Issue by meponqq** [monosans/vk-slaves-bot#10]
Бана нет
![image](https://user-images.githubusercontent.com/63166405/112747840-215c2580-8fe2-11eb-88e1-4231569baa99.png)

**Comment by marmelando** [comment]
Тоже эта проблема, и не даёт поставить работу рабам в ручную, купить рабов можно.

**Comment by ibuypower-xe10** [comment]
+1

**Comment by thedeaddan** [comment]
Разрабы игры что-то поменяли, запросы от бота больше не принимаются, ищем решение

**Comment by linbergxl** [comment]
Ждем-с

**Comment by monosans** [comment]
Исправлено.

**Comment by linbergxl** [comment]
Спасибо Ребят, вы лучшие!
