### ISSUE TITLE
+ошибка+обуление "дал работу, ('balance')" (чек скрин)

### ISSUE THREAD

**Issue by ibuypower-xe10** [monosans/vk-slaves-bot#13]
![image](https://user-images.githubusercontent.com/81510696/112751614-9aa24b00-8fd7-11eb-9bca-b94c7c3db125.png)

буквально только что появилась

**Comment by thedeaddan** [comment]
Эта ошибка была на старой версии бота, ты обновлял до последней? Если да, то создай новый ключ

**Comment by ibuypower-xe10** [comment]
обновил только bot.py . Нужно было всё?

**Comment by thedeaddan** [comment]
_Config.json_ несколько строчек добавилось

**Comment by ibuypower-xe10** [comment]
прикол в том, что всё прекрасно работало. Ошибка просто с ничего появилась. Попробую сейчас обновить.

**Comment by linbergxl** [comment]
+

**Comment by thedeaddan** [comment]
Создай новый ключ. У меня в данный момент все работает

**Comment by linbergxl** [comment]
Я создал новый ключ, то же самое

**Comment by thedeaddan** [comment]
Понял, сообщу разработчику

**Comment by ibuypower-xe10** [comment]
смена ключа не помогла, пытаюсь переустановить

**Comment by ibuypower-xe10** [comment]
меня обнулили

**Comment by thedeaddan** [comment]
Это баг сервиса, попробуй зайти с мобильного интернета или же перезагрузить роутер. Это похоже на бан по ip. **Так же могу заметить, что сервера игры перестали отвечать, судя по логам моих ботов**

**Comment by linbergxl** [comment]
меня тоже обнулили походу)

**Comment by ibuypower-xe10** [comment]
через телефон тоже всё по нулям

**Comment by thedeaddan** [comment]
**СЕРВИС НЕ ОТВЕЧАЕТ.** Не пишите сюда, что вас обнулили. И рекомендую _закрыть вопрос._ Я ответил вам на все ваши вопросы
