### ISSUE TITLE
Снова не работает :)

### ISSUE THREAD

**Issue by asyncdargen** [monosans/vk-slaves-bot#14]

**Comment by Saitochka** [comment]
++

**Comment by damirkaizer** [comment]
+

**Comment by linbergxl** [comment]
та пизда, софт не робит, всех обнулили, кто юзал, ну мы сами виноваты.

**Comment by dmitrashk** [comment]
Я хз что вы делаете такого что вас обнуляет/не работает.
У меня все отлично

**Comment by linbergxl** [comment]
> 
> 
> Я хз что вы делаете такого что вас обнуляет/не работает.
> У меня все отлично
Жди обнуления, там походу волнами банят)

**Comment by monosans** [comment]
Закрыто из-за отсутствия подробного описания проблемы.
