### ISSUE TITLE
ошибка в конфиге ('Expecting value: line 1 column 1 (char 0)',)

### ISSUE THREAD

**Issue by ibuypower-xe10** [monosans/vk-slaves-bot#15]
![image](https://user-images.githubusercontent.com/81510696/112760298-106ddd00-8fff-11eb-8934-9a6452214e0d.png)

**Comment by ibuypower-xe10** [comment]
При этом рабы покупаются

**Comment by ibuypower-xe10** [comment]
проблема ворзникает из-за ошибки в конфиге. min_price > 40 = ошибка

**Comment by ibuypower-xe10** [comment]
также ошибку выдаёт при использовании функции только апгрейдов рабов

**Comment by monosans** [comment]
> также ошибку выдаёт при использовании функции только апгрейдов рабов

Рабы апгрейдятся только при `buy_slaves: 1`.

**Comment by ibuypower-xe10** [comment]
Понял. А на счёт минимальной цены покупки? Я ставил от 60, у меня выдаёт ошибку.

**Comment by ibuypower-xe10** [comment]
И в лооге я не вижу никаких изменений и апрейдов. Только закупка

**Comment by linbergxl** [comment]
ibuypower-xe10, тебя разбанили?

**Comment by ibuypower-xe10** [comment]
так там же не банят, только обнуляют

**Comment by linbergxl** [comment]
м, я когда пытаюсь кого-то купить у меня опять все обнуляется

**Comment by monosans** [comment]
Ошибка происходит из-за слишком высокого значения `"min_price''`. Можете просто игнорировать её.

**Comment by ibuypower-xe10** [comment]
значение `min_price` стоит по дефолту на 40. Скрипт просто не хочет улучшать рабов, только покупает.

**Comment by xR3nd0X** [comment]
> Ошибка происходит из-за слишком высокого значения `"min_price''`. Можете просто игнорировать её.

Если значение min_price больше 40 (даже 60 или 90) - выдаёт ошибку

**Comment by linbergxl** [comment]
То же самое..

**Comment by ibuypower-xe10** [comment]
@linbergxl обнови бота

**Comment by ibuypower-xe10** [comment]
баг с улучшениями пофкшен
