### ISSUE TITLE
минус по балансу и по рабам в логах

### ISSUE THREAD

**Issue by ibuypower-xe10** [monosans/vk-slaves-bot#16]
![image](https://user-images.githubusercontent.com/81510696/112767190-f263a500-901d-11eb-9765-3679ed4c0825.png)
В игре показывает 700 рабов, в логах -9. С доходом тоже самое

**Comment by ibuypower-xe10** [comment]
баг пофиксился самостоятельно. Видимо, проблема была со стороны серверов.

**Comment by vapersan** [comment]
Это тебя обнулили
