### ISSUE TITLE
Проблема с токеном

### ISSUE THREAD

**Issue by DetaileR2033** [monosans/vk-slaves-bot#17]
Бро, какое именно значение вводить в поле токена?

У меня в проге бесконечные строчки slaves и price
Подозреваю, что токен неправильно ввожу

В поле authorization у меня примерно такое
`Bearer vk_access_token_settings=friends,status&vk_app_id=7794757&vk_are_notifications_enabled=1&vk_is_app_user=1&vk_is_favorite=0&vk_language=ru&vk_platform=desktop_web&vk_ref=left_nav&vk_ts=**********&vk_user_id=*********&sign=*******************_******`

![Screenshot_20210329_001531_com termux](https://user-images.githubusercontent.com/58652879/112768291-17f3ad00-9024-11eb-8432-c251c82a7d2e.jpg)

**Comment by ibuypower-xe10** [comment]
Без Bearer! Внимательно читай инструкцию.

**Comment by monosans** [comment]
Ответ комментарием выше.
