### ISSUE TITLE
('Expecting value: line 1 column 1 (char 0)',)

### ISSUE THREAD

**Issue by ripemc** [monosans/vk-slaves-bot#18]
![image](https://user-images.githubusercontent.com/44343034/112783817-dc270a80-9058-11eb-967d-fd1628c1dd45.png)

**Comment by KemuriXXL** [comment]
Пиши в беседу вк.

**Comment by monosans** [comment]
Может быть из-за слишком высокого `min_price`. Ставь 40.

**Comment by ripemc** [comment]
> Может быть из-за слишком высокого `min_price`. Ставь 40.

да, помогло, спасибо.

**Comment by vapersan** [comment]
"min_price": 40
Но проблема осталась
