### ISSUE TITLE
Инструкция на Linux

### ISSUE THREAD

**Issue by ddosenka-now** [monosans/vk-slaves-bot#19]
Что на счёт инструкции на Linux (Ubuntu 20.04 как пример)

**Comment by dmitrashk** [comment]
Тоже самое что и с виндой петон главное поставь

**Comment by monosans** [comment]
Лично я думал, что люди на Linux справятся сами. Процесс идентичен установке на Windows, но тебе нужно установить `python3` и `python3-pip` через **apt** (пакетный менеджер Debian-based дистрибутивов, коим является Ubuntu) или **Synaptic** (графический менеджер пакетов в Ubuntu, насколько знаю).
После этого тебе нужно установить библиотеку requests через pip: `python3 -m pip install requests` в терминале.
Для запуска бота тебе нужно в терминале `cd путь` в директорию с ботом и написать `python3 bot.py`.
Надеюсь, понятно написал.

**Comment by monosans** [comment]
Начиная с версии 3.0 также понадобится `python3 -m pip install fake-useragent`.

**Comment by ddosenka-now** [comment]
Проблема с латиницей, омг..

**Comment by ddosenka-now** [comment]
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 57-62: ordinal not in range(256)
