### ISSUE TITLE
Expecting value и 'balance'

### ISSUE THREAD

**Issue by vadimka04** [monosans/vk-slaves-bot#2]
![image](https://user-images.githubusercontent.com/12530745/112694408-59a11e00-8e93-11eb-91bf-3fe2214df40a.png)
Возможно что проблема в игре потому что при перезагрузке баланс не всегда отображался так что хз

**Comment by thedeaddan** [comment]
_balance_ отображается в том случае, если недостаточно денег на покупку чего либо. А вторая ошибка идёт от декодера JSON и причина её - сервера игры которые отдают не те данные по ошибке. Разработчик как раз занимается этим багом. Возможно днём будет фикс. Обновляйте регулярно бота, так как на старых версиях могут дать бан..

**Comment by thedeaddan** [comment]
Так же эта ошибка идёт из-за того что нет рабов которым можно купить оковы или выдать работу, тоже пофиксим
