### ISSUE TITLE
('Expecting value: line 1 column 1 (char 0)',)

### ISSUE THREAD

**Issue by vapersan** [monosans/vk-slaves-bot#20]
Версия 2.2
Купил оковы vk.com/id266329529
Дал работу vk.com/id266329529

==[29.03.2021 16:38:09]==
Купил vk.com/id66622872 за 40
Баланс: 10,707,813
Рабов: -79
Доход в минуту: -19,477
Место в рейтинге: 4,820,136

('Expecting value: line 1 column 1 (char 0)',)

**Comment by ibuypower-xe10** [comment]
проблема в конфиге

**Comment by monosans** [comment]
Исправлено в новой версии.
