### ISSUE TITLE
('list assignment index out of range',)

### ISSUE THREAD

**Issue by Linegrite** [monosans/vk-slaves-bot#21]
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
Продал id130992766 для улучшения
Улучшил id130992766
('list assignment index out of range',)
        ('list assignment index out of range',)
Продал id130992766 для улучшения

**Comment by monosans** [comment]
Исправлено в версии 3.2.
