### ISSUE TITLE
Проблема с authorization

### ISSUE THREAD

**Issue by snower20** [monosans/vk-slaves-bot#24]
это не по части кода, но через приложение F12 на андроид невозможно взять authorization. Я думаю нужно придумать что то на счёт этого

**Comment by monosans** [comment]
Возможно. Спроси в беседе ВК, как это сделать.

**Comment by anon107** [comment]
> это не по части кода, но через приложение F12 на андроид невозможно взять авторизацию. Я думаю нужно придумать что то на счёт этого

Ты нашёл как это сделать?

**Comment by anon107** [comment]
> Возможно. Спроси в беседе ВК, как это сделать.

В какой беседе нужно спрашивать?

**Comment by monosans** [comment]
> > Возможно. Спроси в беседе ВК, как это сделать.
> 
> В какой беседе нужно спрашивать?

В начале инструкции есть ссылка.

**Comment by Higherupanddown** [comment]
у меня как раз по этой теме вопрос. можно ли сделать запрос get и таким образом через OAuth получить токен?

**Comment by monosans** [comment]
Игра закрыта.
