### ISSUE TITLE
How to choose a specific id? 

### ISSUE THREAD

**Issue by rootpro111** [monosans/vk-slaves-bot#3]
Привет, я хотел настроить бота на конкретную страницу в ВК, но не знаю как это сделать. Если подскажешь буду благодарен.

**Comment by pavelcanton** [comment]
![image](https://user-images.githubusercontent.com/81379149/112707931-7fedaa80-8ee1-11eb-9db8-c631528c03fb.png)
Поменяй на нужный ID, и живи

**Comment by mbutakov** [comment]
@pa

> ![image](https://user-images.githubusercontent.com/81379149/112707931-7fedaa80-8ee1-11eb-9db8-c631528c03fb.png)
> Поменяй на нужный ID, и живи
он наверное имел ввиду чтобы типо с другой странички в вк можно было.

**Comment by thedeaddan** [comment]
Без входа на страницу ты не сделаешь этого, пока что. Возможно в будущем придумаем просто вход через логин и пароль, но это не скоро ;)
