### ISSUE TITLE
Окова и работа

### ISSUE THREAD

**Issue by bouncemew** [monosans/vk-slaves-bot#30]
![IMG_20210330_161418](https://user-images.githubusercontent.com/81470111/112994627-1e446f00-9173-11eb-9d93-60f72b145cad.jpg)
перестал выдавать работы или как я понимаю работу некому дать
и как сделать, когда он выкупил раба сразу посадить на окову, потому что покупает окову через 10 секунд(начинает покупать окову другим левым рабам), в этот момент раба уже выкупают

**Comment by ddosenka-now** [comment]
По оковам вроде работают уже, задержки - проблема сервера рабов
