### ISSUE TITLE
Покупка оков и работы для рабов

### ISSUE THREAD

**Issue by dmitrashk** [monosans/vk-slaves-bot#4]
Почему-то покупает оковы не всем так же и с работами
Как фиксить?

**Comment by thedeaddan** [comment]
У других данной проблемы не наблюдается. Попробуйте сменить токен на новый или же подождать.

**Comment by monosans** [comment]
Покупает оковы и даёт работу всем в том порядке, в каком данные присылает сервер. Чтобы убедиться, что бот действительно даёт работу всем, можете отключить покупку новых рабов и спустя какое-то время увидите, что у всех рабов есть работа.
