### ISSUE TITLE
Спамит id , balance

### ISSUE THREAD

**Issue by meponqq** [monosans/vk-slaves-bot#5]
![image](https://user-images.githubusercontent.com/63166405/112721897-fec20200-8f38-11eb-94b2-0b3842bda65f.png)

**Comment by thedeaddan** [comment]
**Пожалуйста, читайте уже закрытые вопросы.**
Это происходит из-за лагов на сервере игры. Сервер не отдал данные и поэтому бот не смог выдать вам их. И вместо данных показал вам переменную которая не пришла от сервера, но была вызвана. _Данная проблема будет фиксится.._

**Comment by thedeaddan** [comment]
**Закройте вопрос**
